from __future__ import annotations

from dataclasses import asdict, dataclass, is_dataclass
from typing import Any, Mapping


@dataclass(frozen=True)
class OutputContract:
    schema_version: str
    module: str
    artifact: str
    required_fields: tuple[str, ...]
    description: str = ""


REQUIRED_RUNTIME_TRAINING_SCHEMA_VERSIONS = {
    "attack_oracle_output.v1",
    "attack_oracle_failure_validation_report.v1",
    "defense_oracle_output.v1",
    "active_real_query_dispatch_validation.v1",
    "active_real_query_dispatch_validation_report.v1",
    "active_query_feedback_report.v1",
    "daily_training_report.v1",
    "exploiter_effectiveness_report.v1",
    "defense_anti_meta_effectiveness_report.v1",
    "learned_exploiter_validation_report.v1",
    "league_selfplay_health_report.v1",
    "production_readiness_report.v1",
    "v4_conformance_validation_report.v1",
    "mask_explanation_validation_report.v1",
    "belief_real_distribution_validation_report.v1",
    "data_engineering_validation_report.v1",
    "underdog_residual_validation_report.v1",
    "ablation_suite_report.v1",
    "v4_ablation_experiment_plan.v1",
    "training_schedule.v1",
    "training_run_summary.v1",
    "recurring_training_scheduler_state.v1",
    "real_calibration_ingestion_summary.v1",
    "real_calibration_sample_build_summary.v1",
    "real_calibration_validation_report.v1",
    "version_drift_report.v1",
    "run_metadata.v1",
    "core_tables.v1",
    "legality_diagnostics.v1",
}


OUTPUT_CONTRACTS: dict[str, OutputContract] = {
    contract.schema_version: contract
    for contract in (
        OutputContract(
            schema_version="attack_oracle_output.v1",
            module="AttackOracle",
            artifact="AttackOracleOutput.to_json_dict()",
            required_fields=(
                "schema_version",
                "module",
                "metadata",
                "ranked_attack_hashes",
                "ranked_attacks",
                "predicted_scores",
                "simulated_scores",
                "belief_summary",
                "halving_traces",
                "explanation",
                "risk_report",
                "diagnostics",
            ),
            description="Stable mask-aware attack search result.",
        ),
        OutputContract(
            schema_version="attack_oracle_failure_validation_report.v1",
            module="AttackOracleFailureValidationReport",
            artifact="attack_oracle_failure_validation_report.json",
            required_fields=(
                "schema_version",
                "module",
                "oracle_output_paths",
                "round_dirs",
                "oracle_outputs",
                "candidate_rows",
                "candidate_risk_report_rows",
                "checked_rows",
                "failure_rows",
                "annotated_failure_rows",
                "diagnostic_failure_rows",
                "failure_annotation_coverage",
                "failure_diagnostic_coverage",
                "normal_risk_report_rows",
                "failure_stage_counts",
                "failure_code_counts",
                "validation_rows",
                "red_line_violations",
            ),
            description="Validation report for AttackOracle failure annotations and diagnostics.",
        ),
        OutputContract(
            schema_version="defense_oracle_output.v1",
            module="DefenseOracle",
            artifact="DefenseOracleOutput.to_json_dict()",
            required_fields=(
                "schema_version",
                "module",
                "metadata",
                "best_defense_hash",
                "best_defense",
                "backup_defense_hashes",
                "backup_defenses",
                "estimated_attack_success",
                "ambiguity_score",
                "worst_case_attack_hash",
                "worst_case_attack",
                "explanation",
                "risk_report",
                "diagnostics",
            ),
            description="Stable defense roster/mask search result.",
        ),
        OutputContract(
            schema_version="active_real_query_dispatch_validation.v1",
            module="ActiveRealQueryDispatch",
            artifact="validation_report.json",
            required_fields=(
                "schema_version",
                "module",
                "round_dir",
                "out_dir",
                "queued_queries",
                "dispatchable_queries",
                "skipped_queries",
                "dispatched_pairs",
                "oracle_requests",
                "oracle_result_errors",
                "completion_rate",
                "attack_teacher_rows",
                "defense_teacher_rows",
                "teacher_feedback_complete",
                "real_query_queue_validated",
            ),
            description="Validation report for real-query dispatch feedback.",
        ),
        OutputContract(
            schema_version="active_real_query_dispatch_validation_report.v1",
            module="ActiveRealQueryDispatchValidationReport",
            artifact="active_real_query_dispatch_validation_report.json",
            required_fields=(
                "schema_version",
                "module",
                "validation_report_paths",
                "reports",
                "readable_reports",
                "read_error_reports",
                "queued_queries",
                "dispatchable_queries",
                "skipped_queries",
                "skipped_query_reasons",
                "dispatched_pairs",
                "oracle_requests",
                "oracle_result_errors",
                "completion_rate",
                "attack_teacher_rows",
                "defense_teacher_rows",
                "teacher_feedback_complete_reports",
                "real_query_queue_validated_reports",
                "report_rows",
                "red_line_violations",
                "production_ready",
            ),
            description="Scheduler-readable aggregate gate for active real-query dispatch feedback.",
        ),
        OutputContract(
            schema_version="active_query_feedback_report.v1",
            module="ActiveQueryFeedbackReport",
            artifact="active_query_feedback_report.json",
            required_fields=(
                "schema_version",
                "module",
                "round_dir",
                "queries",
                "matched_queries",
                "unmatched_queries",
                "matched_query_coverage",
                "real_queries",
                "matched_real_queries",
                "real_query_feedback_coverage",
                "sim_queries",
                "matched_sim_queries",
                "sim_query_feedback_coverage",
                "oracle_pairs",
                "oracle_result_rows",
                "oracle_result_errors",
                "oracle_result_error_rate",
                "queues",
                "query_feedback",
                "red_line_violations",
            ),
            description="Joined active-query queue and oracle feedback report.",
        ),
        OutputContract(
            schema_version="daily_training_report.v1",
            module="DailyTrainingReport",
            artifact="daily_report.json",
            required_fields=(
                "schema_version",
                "module",
                "date",
                "sim_games",
                "real_matches",
                "single_model",
                "attack_oracle",
                "defense_oracle",
                "league",
                "underdog",
                "active_queries",
                "failure_cases",
            ),
            description="Daily training and round quality report.",
        ),
        OutputContract(
            schema_version="exploiter_effectiveness_report.v1",
            module="ExploiterEffectivenessReport",
            artifact="exploiter_effectiveness_report.json",
            required_fields=(
                "schema_version",
                "teacher_jsonl_paths",
                "teacher_rows",
                "target_feedback_rows",
                "target_feedback_coverage",
                "role_stats",
                "anti_meta",
                "round_stats",
                "trend",
                "red_line_violations",
            ),
            description="Learned exploiter and underdog residual feedback report.",
        ),
        OutputContract(
            schema_version="defense_anti_meta_effectiveness_report.v1",
            module="DefenseAntiMetaEffectivenessReport",
            artifact="defense_anti_meta_effectiveness_report.json",
            required_fields=(
                "schema_version",
                "module",
                "teacher_jsonl_paths",
                "teacher_rows",
                "anti_meta_feedback_rows",
                "anti_meta_feedback_coverage",
                "role_stats",
                "anti_meta",
                "round_stats",
                "trend",
                "red_line_violations",
            ),
            description="Defense-side anti-meta residual feedback report.",
        ),
        OutputContract(
            schema_version="learned_exploiter_validation_report.v1",
            module="LearnedExploiterValidationReport",
            artifact="learned_exploiter_validation_report.json",
            required_fields=(
                "schema_version",
                "module",
                "selfplay_root",
                "training_root",
                "rounds",
                "round_ids",
                "oracle_requests",
                "latest_attack_proposal_checkpoint",
                "latest_defense_proposal_checkpoint",
                "exploiter_report",
                "defense_anti_meta_report",
                "red_line_violations",
                "production_ready",
            ),
            description="Combined learned attack exploiter and defense anti-meta production validation report.",
        ),
        OutputContract(
            schema_version="league_selfplay_health_report.v1",
            module="LeagueSelfPlayHealthReport",
            artifact="league_selfplay_health_report.json",
            required_fields=(
                "schema_version",
                "module",
                "round_dirs",
                "rounds",
                "latest_round_dir",
                "latest_iteration",
                "attack_pool",
                "defense_pool",
                "active_attack_pool",
                "active_defense_pool",
                "active_pool_fraction",
                "attack_clusters",
                "defense_clusters",
                "total_clusters",
                "attack_role_counts",
                "defense_role_counts",
                "attack_role_coverage",
                "defense_role_coverage",
                "payoff_entries",
                "payoff_density",
                "new_attack_strength_delta",
                "new_defense_strength_delta",
                "round_reports",
                "red_line_violations",
                "production_ready",
            ),
            description="LeagueManager/PSRO health gate over pools, roles, payoff coverage, diversity, and retention.",
        ),
        OutputContract(
            schema_version="production_readiness_report.v1",
            module="ProductionReadinessReport",
            artifact="production_readiness_report.json",
            required_fields=(
                "schema_version",
                "module",
                "report_paths",
                "reports",
                "readable_reports",
                "read_error_reports",
                "clean_reports",
                "red_line_reports",
                "clean_report_rate",
                "production_ready_checked_reports",
                "production_ready_reports",
                "production_ready_false_reports",
                "schema_counts",
                "required_schema_versions",
                "missing_required_schema_versions",
                "report_rows",
                "red_line_violations",
                "production_ready",
            ),
            description="Cross-report production readiness gate for v4 validation outputs.",
        ),
        OutputContract(
            schema_version="v4_conformance_validation_report.v1",
            module="V4ConformanceValidationReport",
            artifact="v4_conformance_validation_report.json",
            required_fields=(
                "schema_version",
                "module",
                "report_paths",
                "reports",
                "readable_reports",
                "read_error_reports",
                "schema_counts",
                "requirements_total",
                "passed_requirements",
                "failed_requirements",
                "requirements",
                "report_rows",
                "red_line_violations",
                "production_ready",
            ),
            description="Requirement-level v4 conformance evidence gate over production validation priorities.",
        ),
        OutputContract(
            schema_version="mask_explanation_validation_report.v1",
            module="MaskExplanationValidationReport",
            artifact="mask_explanation_validation_report.json",
            required_fields=(
                "schema_version",
                "module",
                "round_dir",
                "defenses",
                "risk_report_rows",
                "mask_explanation_rows",
                "learned_mask_score_rows",
                "counter_attack_risk_rows",
                "defenses_with_no_hidden_slots",
                "total_hidden_slots",
                "explained_hidden_slots",
                "hidden_explanation_coverage",
                "mean_hidden_count",
                "mean_learned_mask_score",
                "defense_rows",
                "red_line_violations",
            ),
            description="Validation report for learned mask explanations and counter-attack risk coverage.",
        ),
        OutputContract(
            schema_version="belief_real_distribution_validation_report.v1",
            module="BeliefRealDistributionValidationReport",
            artifact="belief_real_distribution_validation_report.json",
            required_fields=(
                "schema_version",
                "module",
                "round_dir",
                "candidates",
                "belief_domain_stats_rows",
                "real_distribution_rows",
                "real_distribution_coverage",
                "exact_real_rows",
                "similar_real_rows",
                "mean_real_record_count",
                "mean_real_similarity",
                "mean_real_match_result",
                "mean_weight_entropy_normalized",
                "oracle_alignment_rows",
                "oracle_alignment_mae",
                "candidate_rows",
                "red_line_violations",
            ),
            description="Validation report for belief real-distribution similarity usage and oracle alignment.",
        ),
        OutputContract(
            schema_version="data_engineering_validation_report.v1",
            module="DataEngineeringValidationReport",
            artifact="data_engineering_validation_report.json",
            required_fields=(
                "schema_version",
                "module",
                "round_dirs",
                "rounds",
                "metadata_files",
                "metadata_coverage",
                "artifact_refs",
                "artifact_verified",
                "artifact_missing_count",
                "artifact_hash_mismatch_count",
                "artifact_hash_coverage",
                "core_table_files_expected",
                "core_table_files_found",
                "core_table_coverage",
                "core_table_empty_count",
                "core_table_schema_mismatch_count",
                "round_reports",
                "red_line_violations",
            ),
            description="Validation report for run metadata, artifact hashes, and core table coverage.",
        ),
        OutputContract(
            schema_version="underdog_residual_validation_report.v1",
            module="UnderdogResidualValidationReport",
            artifact="underdog_residual_validation_report.json",
            required_fields=(
                "schema_version",
                "module",
                "round_dirs",
                "rounds",
                "attack_rows",
                "attack_underdog_rows",
                "attack_residual_rows",
                "attack_residual_coverage",
                "mean_attack_underdog_gap",
                "mean_attack_residual_bonus",
                "mean_attack_objective_score",
                "defense_rows",
                "defense_underdog_rows",
                "defense_residual_rows",
                "defense_residual_coverage",
                "mean_defense_underdog_gap",
                "mean_defense_residual_bonus",
                "mean_defense_objective_score",
                "round_reports",
                "red_line_violations",
            ),
            description="Production validation report for attack and defense underdog residual objective coverage.",
        ),
        OutputContract(
            schema_version="ablation_suite_report.v1",
            module="AblationSuiteReport",
            artifact="ablation_suite_report.json",
            required_fields=(
                "schema_version",
                "module",
                "suite_id",
                "date",
                "baseline_variant",
                "variants",
                "missing_required_variants",
                "variant_reports",
                "deltas_vs_baseline",
            ),
            description="Cross-variant v4 ablation report.",
        ),
        OutputContract(
            schema_version="v4_ablation_experiment_plan.v1",
            module="AblationExperimentPlan",
            artifact="v4_ablation_experiment_plan.json",
            required_fields=(
                "schema_version",
                "suite_id",
                "root_dir",
                "baseline_variant",
                "required_variants",
                "missing_required_variants",
                "variants",
            ),
            description="Executable v4 ablation experiment plan.",
        ),
        OutputContract(
            schema_version="training_schedule.v1",
            module="TrainingSchedule",
            artifact="schedule.json",
            required_fields=("schema_version", "module", "schedule_id", "root_dir", "registry_path", "created_at", "jobs", "metadata"),
            description="Training job DAG.",
        ),
        OutputContract(
            schema_version="training_run_summary.v1",
            module="TrainingRunSummary",
            artifact="status.json",
            required_fields=("schema_version", "module", "schedule_id", "executed", "jobs"),
            description="Training schedule execution status.",
        ),
        OutputContract(
            schema_version="recurring_training_scheduler_state.v1",
            module="RecurringTrainingSchedulerState",
            artifact="scheduler_state.json",
            required_fields=("schema_version", "module", "scheduler_id", "root_dir", "stopped", "stop_reason", "next_run_at", "iterations"),
            description="Recurring scheduler state and stop reason.",
        ),
        OutputContract(
            schema_version="real_calibration_ingestion_summary.v1",
            module="RealCalibrationIngestionSummary",
            artifact="real_calibration_report.json",
            required_fields=(
                "schema_version",
                "module",
                "round_dir",
                "db_path",
                "round_id",
                "records_added",
                "skipped_pairs",
                "mean_match_result",
                "season",
                "server",
                "source_kind",
            ),
            description="League round or active real-query feedback ingestion into RealMetaDB.",
        ),
        OutputContract(
            schema_version="real_calibration_sample_build_summary.v1",
            module="RealCalibrationSampleBuildSummary",
            artifact="real_calibration_samples_report.json",
            required_fields=(
                "schema_version",
                "module",
                "out_jsonl",
                "source_dirs",
                "samples_written",
                "skipped_pairs",
                "mean_label",
                "mean_sim_probability",
                "source_kinds",
            ),
            description="Real calibration sample JSONL build summary from round and active real-query artifacts.",
        ),
        OutputContract(
            schema_version="real_calibration_validation_report.v1",
            module="RealCalibrationValidationReport",
            artifact="real_calibration_validation_report.json",
            required_fields=(
                "schema_version",
                "module",
                "samples_jsonl",
                "calibration_json",
                "samples",
                "labels_mean",
                "raw_prediction_mean",
                "base_prediction_mean",
                "calibrated_prediction_mean",
                "raw_brier",
                "base_brier",
                "calibrated_brier",
                "brier_improvement",
                "base_brier_improvement",
                "raw_ece",
                "base_ece",
                "calibrated_ece",
                "ece_improvement",
                "base_ece_improvement",
                "feature_names",
                "red_line_violations",
                "production_ready",
            ),
            description="Holdout validation report proving real calibration improves Brier/ECE over raw simulator probabilities.",
        ),
        OutputContract(
            schema_version="version_drift_report.v1",
            module="VersionDriftReport",
            artifact="real_calibration_report.json",
            required_fields=(
                "schema_version",
                "module",
                "baseline_season",
                "current_season",
                "baseline_records",
                "current_records",
                "baseline_mean_match_result",
                "current_mean_match_result",
                "match_result_delta",
                "observation_overlap",
                "drift_detected",
            ),
            description="Season/version drift report for real calibration data.",
        ),
        OutputContract(
            schema_version="run_metadata.v1",
            module="RunMetadataManifest",
            artifact="run_metadata.json",
            required_fields=(
                "schema_version",
                "run_id",
                "created_at",
                "code_version",
                "model_version",
                "data_version",
                "simulator_version",
                "league_iteration",
                "random_seed",
                "generation_config_hash",
                "calibration_version",
                "input_artifacts",
                "output_artifacts",
                "metrics",
                "extra",
            ),
            description="Reproducibility manifest for simulation/training runs.",
        ),
        OutputContract(
            schema_version="core_tables.v1",
            module="CoreTables",
            artifact="tables/*.jsonl",
            required_fields=("schema_version", "table"),
            description="Persistent data-engineering JSONL tables.",
        ),
        OutputContract(
            schema_version="legality_diagnostics.v1",
            module="ConstraintEngine",
            artifact="LegalReport.to_json_dict()",
            required_fields=("schema_version", "legal", "reasons", "diagnostics"),
            description="Stable legality rejection diagnostics.",
        ),
    )
}


def output_contract_registry() -> tuple[OutputContract, ...]:
    return tuple(OUTPUT_CONTRACTS[key] for key in sorted(OUTPUT_CONTRACTS))


def jsonable(value: Any) -> Any:
    if is_dataclass(value):
        return jsonable(asdict(value))
    if isinstance(value, Mapping):
        return {str(key): jsonable(item) for key, item in value.items()}
    if isinstance(value, (tuple, list)):
        return [jsonable(item) for item in value]
    if isinstance(value, (set, frozenset)):
        return sorted(jsonable(item) for item in value)
    return value


def failure_diagnostics(payload: Mapping[str, Any]) -> list[dict[str, Any]]:
    failure = payload.get("failure")
    if failure is None:
        return []
    code = str(payload.get("failure_code") or "MODULE_FAILURE")
    diagnostic = {
        "code": code,
        "message": str(failure),
        "severity": "error",
    }
    if payload.get("failure_stage") is not None:
        diagnostic["stage"] = str(payload["failure_stage"])
    if payload.get("failure_context") is not None:
        diagnostic["context"] = payload["failure_context"]
    return [
        diagnostic
    ]
